---
- name: configuration play 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  gather_facts: false
  tasks:

  - name: copy files
    copy:
      src: ./
      dest: github/

  - name: start nginx container
    become: yes
    shell: |
      cd github
      docker image ls
      docker compose up -d --build
      docker image prune