---
- name: configuration play 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  gather_facts: false
  tasks:

  - name: Get/Update Code
    become: yes
    git:
      repo: git clone git@github.com:Fouty7/github-action.git
      dest: /home/ubuntu/github-action
      accept_hostkey: yes
      clone: yes
      update: yes
   
  - name: start docker compose
    become: yes
    shell: |
      cd github-action
      docker image ls
      docker compose up -d --build

  - name: cleanup old images
    become: yes
    ignore_errors: true
    shell: |
      docker rmi $(docker images --filter "dangling=true" -q --no-trunc)