---
- name: configuration play 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  gather_facts: false
  tasks:
  
  - name: Install Docker
    become: yes
    shell: |
      apt update
      apt install apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
      sudo apt install docker-ce -y
      sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      sudo chmod +x /usr/local/bin/docker-compose
  - name: Get/Update Code
    become: yes
    git:
      repo: git@github.com:Fouty7/github-action.git
      dest: /home/ubuntu/github-action
      accept_hostkey: yes
      key_file: ~/.ssh/id_rsa
      clone: yes
      update: yes

  - name: start docker compose
    become: yes
    shell: |
      cd github-action
      docker image ls
      docker compose up -d --build

  - name: cleanup old images
    become: yes
    ignore_errors: true
    shell: |
      docker rmi $(docker images --filter "dangling=true" -q --no-trunc)