version: '3.5'

services:
    nodejs-app:
        build:
          context: ./node-app
        image: aminfourty7/githubaction-nodejs:latest  
        container_name: githubaction-nodejs-app
        hostname: nodejs-app
        ports:
            - "3000:3000"  
    nginx:
        build:
          context: ./nginx
        image: aminfourty7/githubaction-nginx:latest  
        container_name: githubaction-nginx
        hostname: nginx
        ports:
            - "8080:80" 
        depends_on:
            - nodejs-app