name: workflow nodejs-app

on:
  push:
    branches: [ main ]

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build-nodejs-image
        run: |
          
          docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -t aminfourty7/githubaction-nodejs:latest .
          docker push aminfourty7/githubaction-nodejs:latest
      - name: build-nginx-image
        run: |
          cd nginx
          docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -t aminfourty7/githubaction-nginx:latest .
          docker push aminfourty7/githubaction-nginx:latest
      - name: Report Fail
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          notification_title: '{workflow} has {status_message}'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}     

  get-ec2-ip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: get ip    
        run: |
          aws ec2 describe-instances \
          --query 'Reservations[*].Instances[*].PublicIpAddress' \
          --filters "Name=tag:project,Values=docker-server" \
          --output text >> inventory
          cat inventory
      - name: persist workspace
        uses: actions/upload-artifact@v3
        with:
          name: inventory
          path: inventory
      - name: Report Fail
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}

  run-ansible:
    runs-on: ubuntu-latest
    needs: [get-ec2-ip]
    steps:
      - uses: actions/checkout@v2    
 
      - name: get ssh key
        uses: webfactory/ssh-agent@v0.6.0
        with:
            ssh-private-key: ${{ secrets.AWS_PRIVATE_KEY }}
      
      - name: Install dependencies
        run: sudo apt-get install ansible tar gzip

      - name: Attach workspace
        uses: actions/download-artifact@v3
        with:
          name: inventory

      - name: run containers
        run: ansible-playbook -i inventory docker-ansible.yaml
      - name: Report Fail
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - name: Report Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}